run_name = "v5"
default_root_dir = "runs/v5"

datasets = [
  'C:\Users\Felix\OneDrive\Documents\thrawn-nnue\data\T60T70wIsRightFarseer.binpack',
]

validation_datasets = [
  'C:\Users\Felix\OneDrive\Documents\thrawn-nnue\data\T60T70wIsRightFarseer.binpack',
]
validation_size = 1000000
check_val_every_n_epoch = 1

accelerator = "cuda"
num_workers = 4
threads = 2
batch_size = 16384
pin_memory = true
data_loader_queue_size = 8
tf32 = true
fused_optimizer = true
seed = 42

max_epochs = 40
epoch_size = 100000000
network_save_period = 10
save_last_network = true
console_mode = "progress"

features = "HalfKAv2_hm^"
num_features = 24576
num_factor_features = 768
max_active_features = 32
ft_size = 1024
l1_size = 256
l2_size = 64

filtered = true
wld_filtered = true
random_fen_skipping = 3

optimizer_name = "adamw"
lr = 0.0004375
gamma = 0.995
weight_decay = 0.0
clip_grad_norm = 10.0
amp = true

nnue2score = 600.0
start_lambda = 1.0
end_lambda = 0.75
in_offset = 270.0
in_scaling = 340.0
out_offset = 270.0
out_scaling = 380.0
pow_exp = 2.5

network_testing_nodes_per_move = 20000
export_ft_scale = 127.0
export_dense_scale = 64.0
export_description = "thrawn halfka v2 hm nnue T60 T70 IsRight Farseer fine tune"
