run_name = "v5"
default_root_dir = "runs/v5"

datasets = [
  '../data/T60T70wIsRightFarseer.binpack',
]
validation_size = 1000000
check_val_every_n_epoch = 1

accelerator = "cuda"
num_workers = 4
batch_size = 16384
pin_memory = true
data_loader_queue_size = 8
tf32 = true
fused_optimizer = true
seed = 42

max_epochs = 100
epoch_size = 100000000
network_save_period = 1
save_last_network = true
console_mode = "progress"

features = "HalfKAv2_hm"

filtered = true
wld_filtered = true
random_fen_skipping = 3
early_fen_skipping = -1
soft_early_fen_skipping = 20
simple_eval_skipping = -1
pc_y0 = 0.0
pc_y1 = 0.4
pc_y2 = 1.0
pc_y3 = 1.0
pc_y4 = 0.75
ply_x1 = 0.0
ply_y1 = 0.1
ply_x2 = 6.0
ply_y2 = 0.15
ply_x3 = 10.0
ply_y3 = 0.25
ply_x4 = 18.0
ply_y4 = 0.75

lr = 0.0002
gamma = 0.997
clip_grad_norm = 10.0
amp = true

nnue2score = 600.0
start_lambda = 1.0
end_lambda = 0.75
in_offset = 270.0
in_scaling = 340.0
out_offset = 270.0
out_scaling = 380.0
pow_exp = 2.5

export_description = "thrawn HalfKAv2_hm 1024x2 -> 31+1 -> 32 -> 1 T60 T70 IsRight Farseer 200ep fine tune"
