run_name = "v6"
default_root_dir = "runs/v6"

datasets = [
  'C:\Users\Felix\OneDrive\Documents\thrawn-nnue\data\test80-2023-01-jan-16tb7p.v6-sk20.min.binpack',
]

validation_datasets = [
  'C:\Users\Felix\OneDrive\Documents\thrawn-nnue\data\test80-2023-01-jan-16tb7p.v6-sk20.min.binpack',
]
validation_size = 1000000
check_val_every_n_epoch = 1

accelerator = "cuda"
num_workers = 4
threads = 2
batch_size = 16384
pin_memory = true
data_loader_queue_size = 8
tf32 = true
fused_optimizer = true
seed = 42

max_epochs = 20
epoch_size = 100000000
network_save_period = 10
save_last_network = true
console_mode = "progress"

features = "HalfKAv2_hm"
num_features = 22528
max_active_features = 32
ft_size = 1024
hidden_size = 31
forward_size = 1
fc1_output_size = 32

filtered = true
wld_filtered = true
random_fen_skipping = 3

optimizer_name = "adamw"
lr = 0.00005
gamma = 0.997
weight_decay = 0.0
clip_grad_norm = 10.0
amp = true

nnue2score = 600.0
start_lambda = 1.0
end_lambda = 0.75
in_offset = 270.0
in_scaling = 340.0
out_offset = 270.0
out_scaling = 380.0
pow_exp = 2.5

network_testing_nodes_per_move = 20000
export_ft_scale = 255.0
export_dense_scale = 64.0
export_description = "thrawn HalfKAv2_hm 1024x2 -> 31+1 -> 32 -> 1 Test80 Jan 2023 sk20 polish fine tune"
